repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.25.1
    hooks:
      - id: pyupgrade
        args: ['--py3-plus']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: flake8
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 4.3.21
    hooks:
      - id: isort
